/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * 
 * 
 */

// todo final
// alpha 1 point, poliline for path + win con
// alpha 2 grid + haul gui right hbox with status + console view threaded
// complete all todo optimizations + input player and ai input
package it.unicam.cs.formula1.app;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(JavaFXView.class);
    }
}
