/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.app;


public class App {
    public static void main(String[] args) {

        SetupController controller = new SetupController();

        controller.setup(args[0], args[1]);
        try{
            controller.run();
        }
        catch(InterruptedException e) {
            System.out.println("sleep exception");
        }
    }
}
