/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":api"))
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml")
}

application {
    // Define the main class for the application.
    mainClass = "it.unicam.cs.app.App"
}
